<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageIcon>JFA.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/javlonfattoev/JFA.DependencyInjection</RepositoryUrl>
    <PackageTags>di, dependency injection, auto, extension</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Authors>Javlon Fattoev</Authors>
    <Company>JFA</Company>
    <Title>Register services according to container with service lifetime attributes</Title>
    <Description>Register services according to container with service lifetime attributes</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>9.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\JFA.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="JFA.DependencyContainer" Version="9.0.0" />
  </ItemGroup>

</Project>
